### ISSUE TITLE
Options Menu fixes

### ISSUE THREAD

**Issue by exactlyallan** [AjayThorve/morpheus-fingerprint-viz#1]
- [x] Make background transparent like anomaly details menu
- [x] Move options menu background to meet bottom of nav bar (remove gap)
- [x] Add Info hover-over icon like anomaly details menu for each option
- [x] Suggestion: Move or add 'loading' icon animation from status bar into 'apply' button ( prevents user from reclicking applied options when request takes a few seconds )
- [x] Add hex bar height scale slider (0-100)

**Comment by AjayThorve** [comment]
done with all these
