### ISSUE TITLE
Readme Updates

### ISSUE THREAD

**Issue by exactlyallan** [AjayThorve/morpheus-fingerprint-viz#4]
- [x] Update screenshots
- [x] Add requirement section - i.e. cuda-toolkit, nvidia GPU
- [x] Add section describing .env options
- [x] Add troubleshooting section - i.e. note about OOM issues, common install issues 
- [x] Add link and note about Node RAPIDS

**Comment by LoftyDroid** [comment]
Hi @exactlyallan, can you plz assign this to me?

**Comment by AjayThorve** [comment]
done
